### ISSUE TITLE
Card idea: useR! bingo

### ISSUE THREAD

**Issue by jennybc** [jennybc/bingo#4]
Conference bingo is a fine, fine tradition. Why not for useR?

Google search to get you inspired:

<http://www.google.com/search?q=conference+bingo>

**Comment by jennybc** [comment]
Context: Participants in the [Git + GitHub + R + RStudio tutorial](http://schedule.user2016.org/event/7Bad/using-git-and-github-with-r-rstudio-and-r-markdown-part-1) at useR will be invited to take what they find here and make a pull request on this repo as their final activity.

**Comment by bearloga** [comment]
The phrase "R vs. Python"

**Comment by corynissen** [comment]
"hadleyverse" 
"pipe"

**Comment by rmflight** [comment]
rmarkdown
shiny
bookdown

**Comment by Luke4130** [comment]
grammar of
r inferno

**Comment by barryrowlingson** [comment]
List from my "bingoer" package:

   "%>%",
    "CRANdalf",
    "shiny",
    "RConsortium",
    "mtcars",
    "diamonds",
    "Hadleyverse",
    "ArrCeePeePee",
    "cats",
    "kittens",
    "StackOverflow",
    "Data Science",
    "rainbow",
    "pie chart",
    "SAS",
    "SPSS",
    "Excel",
    "R4",
    "R5",
    "R6",
    "Splus",
    "Tibco",
    "R-forge",
    "library!=package",
    "%<>%",
    "sell out",
    "cloud",
    "language war",
    "Julia",
    "R-bloggers",
"analytics"

**Comment by jennybc** [comment]
Turns out @barryrowlingson had already made something for R conference bingo!

He has [generously said it's ok](https://twitter.com/geospacedman/status/745343455413567488) to mine his squares for use over  here:

https://github.com/barryrowlingson/bingoer/blob/master/R/card.R

**Comment by jennybc** [comment]
from @yanlesin

docker

**Comment by corynissen** [comment]
A failed live demo
two people exchanging business cards
"in the cloud"
"AWS"
A laptop with > 5 R themed stickers
A t-shirt from a past R conference
Microsoft Windows running on a PC
Somebody coding in emacs / vi

**Comment by hrbrmstr** [comment]
spark / sparkr
notebook
repo
base (as in base vs ggplot2)
virtually every dplyr verb

and i'll mine the userR site abstracts in a bit :-)

**Comment by spholmes** [comment]
literate
sankey
contour
flowchart
reproducible
interactive
stata
structural equation
credible

**Comment by trestletech** [comment]
"big data"
"subversion"
"cloud scale"
Beamer slides
"RForge"

**Comment by daattali** [comment]
thanks for the suggestions everyone! I incorporated all of them, if anybody has any more suggestions please add them directly into the card with a PR on [the card file](https://github.com/jennybc/bingo/blob/master/inst/topics/useR-2016.R)

**Comment by jennybc** [comment]
@daattali Did you see the reason for opening this issue?

**Comment by kylehamilton** [comment]
"shiny"
"Is that Hadley Wickham"

**Comment by petestmarie** [comment]
Bayesian

**Comment by daattali** [comment]
Thanks for all the suggestions everyone! I've added a file with all the suggestions you gave here.  If anyone wants to keep contributing, please add new words directly to the [word file](https://github.com/jennybc/bingo/blob/master/inst/topics/useR-conf.R) and submit a PR
