### ISSUE TITLE
Add instructions for contributing a card

### ISSUE THREAD

**Issue by jennybc** [jennybc/bingo#5]
@daattali Thanks for prepping this repo a bit more. Will you add explicit instructions for what a PR should look like to add a bingo card? Maybe make a "contributing.md" file for this?

**Comment by jennybc** [comment]
It would be nice to track who contributed what in a way that's not just via the git history, but also lighter weight than DESCRIPTION. What if we used NEWS.md for that? People could then practice adding a bullet point about their contribution?

**Comment by daattali** [comment]
I'll add a contributing.md later.  People can put their name as a comment
in the R file they upload.  Is that enough, or do you want to use NEWS.md?

---
http://deanattali.com

**Comment by jennybc** [comment]
Sure that's fine, scratch the NEWS.md plan.

I recently took a look at how you refactored things (but after I created this issue) and now I see the squares got moved into files below `inst/topics`. So yes the instructions should indicate that a file with new squares needs to have a comment at the top with info on source, contributors, etc.

**Comment by daattali** [comment]
done
